### ISSUE TITLE
  [ReflectionException]   Class Doctrine\ORM\EntityManagerInterface does not exist

### ISSUE THREAD

**Issue by akrick** [nordsoftware/lumen-rbac#17]
after i excute php artisan , it appears to be like that 
   [ReflectionException]
  Class Doctrine\ORM\EntityManagerInterface does not exist

**Comment by Jalle19** [comment]
You'll need to add Doctrine as a dependency too, this library doesn't work without it.

**Comment by Jalle19** [comment]
Kinda fixed in https://github.com/digiaonline/lumen-rbac/commit/d41baa2b8d22ac98610d07dd67b00956455d7ca4
